#!/usr/bin/env bash

hash pwsh 2>/dev/null || {
	echo >&2 "I require powershell but it's not installed. "
	exit 1
}

Xrealfile=$(realpath "$0")
PrefixDir=$(dirname "$Xrealfile")
pwsh -NoLogo -NoProfile -File "$PrefixDir/devops.ps1" "$@"
